x-base:
  &base
  networks:
    - friendroom_net
  restart: always

services:
  postgres:
    <<: *base
    image: postgres:14.5-alpine
    restart: always
    shm_size: 2gb
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime/:ro
  redis:
    <<: *base
    command: redis-server --save 20 1 --loglevel warning --requirepass friendroom
    volumes:
      - ./data/redis:/data
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    <<: *base
    image: rabbitmq:3.11.0-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - './data/rabbitmq:/var/lib/rabbitmq'
      - '/etc/localtime:/etc/localtime/:ro'

networks:
  friendroom_net:
    driver: bridge

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  rabbitmq:
    driver: local
